### ISSUE TITLE
new version roadmap

### ISSUE THREAD

**Issue by ebokai** [ebokai/particle_game_of_life#10]
simulation
- [x] add collisions
- [x] stabilize particles
- [ ] rescale parameters to O(1)
- [x] change trig to linear algebra
- [ ] recover swimming behaviour

interactivity
- [ ] add particles via mouse click
- [x] control parameters in real-time
- [x] reset simulation

debug
- [ ] velocity vectors
- [x] spatial grid + members
- [ ] turn off interactions, friction, collision, etc...

graphics
- [x] faster circle rendering
- [ ] anti-aliasing
- [ ] better visual fidelity and control
- [ ] on-screen frame rate
